### ISSUE TITLE
Windows build pipeline fails if USE_ADOPT_SHELL_SCRIPTS is false

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/ci-jenkins-pipelines#1172]
One might use USE_ADOPT_SHELL_SCRIPT = false to test their own ci.jenkins.pipelines branch, however when running a windows build it causes the build to fail during the signing stage

https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-windows-x64-temurin/242/console

```
[Pipeline] echo
14:47:43  Execution error: hudson.AbortException: No such saved stash ‘jmods’
[Pipeline] echo
14:47:43  hudson.AbortException: No such saved stash ‘jmods’
14:47:43  	at PluginClassLoader for workflow-api//org.jenkinsci.plugins.workflow.flow.StashManager.unstash(StashManager.java:160)
14:47:43  	at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:78)
14:47:43  	at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:65)
14:47:43  	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
14:47:43  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
14:47:43  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
14:47:43  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
14:47:43  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
14:47:43  	at java.base/java.lang.Thread.run(Thread.java:840)
```

Disabling the signing, `"ENABLE_SIGNER": false`, bypasses this https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/413/console

**Comment by Haroon-Khel** [comment]
Applies to mac too https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-mac-x64-temurin/186/console
