### ISSUE TITLE
Bug: PR-test jobs in Jenkins not working with GitHubCommitStatusSetter

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#311]
**What are you trying to do?**
PR test  jobs not working, we cannot use Jenkins to get change made in this repo. 
Checking Github status is only used in interla PR tests, so it is not breaking "production" builds.
The last "green" PR test was made on 12th May, and first failed on 19th May

**Expected behaviour:**
Job can run without error

**Observed behaviour:**
see log: https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk18u/job/jdk18u-alpine-linux-x64-temurin/5/console
`java.lang.NoSuchMethodError: 'com.google.common.hash.Hasher com.google.common.hash.Hasher.putString(java.lang.CharSequence)'
	at org.jenkinsci.plugins.github.internal.GitHubClientCacheOps$ToCacheDir.hashed(GitHubClientCacheOps.java:164)
	at org.jenkinsci.plugins.github.internal.GitHubClientCacheOps$ToCacheDir.applyNullSafe(GitHubClientCacheOps.java:153)
	at org.jenkinsci.plugins.github.internal.GitHubClientCacheOps$ToCacheDir.applyNullSafe(GitHubClientCacheOps.java:145)
	at org.jenkinsci.plugins.github.util.misc.NullSafeFunction.apply(NullSafeFunction.java:18)
	at org.jenkinsci.plugins.github.internal.GitHubLoginFunction.connector(GitHubLoginFunction.java:114)
	at org.jenkinsci.plugins.github.internal.GitHubLoginFunction.applyNullSafe(GitHubLoginFunction.java:65)
	at org.jenkinsci.plugins.github.internal.GitHubLoginFunction.applyNullSafe(GitHubLoginFunction.java:44)
	at org.jenkinsci.plugins.github.util.misc.NullSafeFunction.apply(NullSafeFunction.java:18)
	at org.jenkinsci.plugins.github.config.GitHubServerConfig$ClientCacheFunction.applyNullSafe(GitHubServerConfig.java:418)
	at org.jenkinsci.plugins.github.config.GitHubServerConfig$ClientCacheFunction.applyNullSafe(GitHubServerConfig.java:414)
	at org.jenkinsci.plugins.github.util.misc.NullSafeFunction.apply(NullSafeFunction.java:18)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:826)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:669)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:668)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1395)
	at com.google.common.collect.Iterators.addAll(Iterators.java:366)
	at com.google.common.collect.Lists.newArrayList(Lists.java:147)
	at com.google.common.collect.Lists.newArrayList(Lists.java:133)
	at org.jenkinsci.plugins.github.util.FluentIterableWrapper.toList(FluentIterableWrapper.java:147)
	at org.jenkinsci.plugins.github.status.sources.ManuallyEnteredRepositorySource.repos(ManuallyEnteredRepositorySource.java:51)
	at org.jenkinsci.plugins.github.status.GitHubCommitStatusSetter.perform(GitHubCommitStatusSetter.java:136)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829`
**Any other comments:**
This might related to the upgrade of github plugin or Jenkins core(?) or too old verison og github plugin(?)
Not been able to identify [code](https://github.com/jenkinsci/github-plugin/) which change caused this yet
from https://github.com/jenkinsci/github-plugin/blob/b1482bd800a49fb2519d4d5525dd8e22f1870d1c/src/main/java/org/jenkinsci/plugins/github/internal/GitHubClientCacheOps.java#L165 -> https://github.com/google/guava/blob/b1a86797e10d18a59ad2a6a3fb20900d2ebb96fd/guava/src/com/google/common/hash/Hasher.java#L107 indicate, putString() has been changed,  but if Jenkins complain: not find putString(java.lang.CharSequence) which mean, it still uses an old version guava ?

**Comment by zdtsw** [comment]
@karianna @sxa would you mind taking a look at this issue next week if it is related to jenkins upgrade?
