### ISSUE TITLE
reproduce_compare build failed with 'java.nio.file.NoSuchFileException'

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/ci-jenkins-pipelines#730]
```
hudson.remoting.ProxyException: java.nio.file.NoSuchFileException: /home/jenkins/.jenkins/jobs/build-scripts-pr-tester/jobs/build-test/jobs/jobs/jobs/jdk17u/jobs/jdk17u-linux-x64-temurin/builds/135/archive/workspace/target/OpenJDK17U-jdk_x64_linux_hotspot_2023-06-13-15-16.tar.gz
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:257)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:168)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.Files.getPosixFilePermissions(Files.java:2125)
	at hudson.util.IOUtils.mode(IOUtils.java:135)
	at jenkins.util.VirtualFile$FileVF.mode(VirtualFile.java:720)
	at hudson.plugins.copyartifact.CopyArtifact.copyOne(CopyArtifact.java:762)
Caused: hudson.remoting.ProxyException: java.io.IOException: Failed to copy file:/home/jenkins/.jenkins/jobs/build-scripts-pr-tester/jobs/build-test/jobs/jobs/jobs/jdk17u/jobs/jdk17u-linux-x64-temurin/builds/135/archive/workspace/target/OpenJDK17U-jdk_x64_linux_hotspot_2023-06-13-15-16.tar.gz to /home/jenkins/workspace/jdk17u-linux-x64-temurin_reproduce_compare/original/OpenJDK17U-jdk_x64_linux_hotspot_2023-06-13-15-16.tar.gz

```
https://ci.adoptium.net/job/jdk17u-linux-x64-temurin_reproduce_compare/7/console

**Comment by sophia-guo** [comment]
Job configuration is using the stale personal branch. Updated. No this issue.
