### ISSUE TITLE
jdk17u x64Linux build artifact failed to be copied

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#808]
https://ci.adoptium.net/job/build-scripts/job/openjdk17-pipeline/766/consoleFull
fails to copy artifact from downstream build job: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-linux-x64-temurin/405/console
```
[Pipeline] copyArtifacts
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
02:10:43  ERROR: Error during copy and archive artifacts for build job: build-scripts/jobs/jdk17u/jdk17u-linux-x64-temurin
02:10:43  java.nio.file.NoSuchFileException: /home/jenkins/.jenkins/jobs/build-scripts/jobs/jobs/jobs/jdk17u/jobs/jdk17u-linux-x64-temurin/builds/405/archive/workspace/target/OpenJDK17U-jdk-sources_2023-09-05-23-30.tar.gz
02:10:43  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
02:10:43  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
02:10:43  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
02:10:43  	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:257)
02:10:43  	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:168)
02:10:43  	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
02:10:43  	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
02:10:43  	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
02:10:43  	at java.base/java.nio.file.Files.getPosixFilePermissions(Files.java:2125)
02:10:43  	at hudson.util.IOUtils.mode(IOUtils.java:135)
02:10:43  	at jenkins.util.VirtualFile$FileVF.mode(VirtualFile.java:720)
02:10:43  	at hudson.plugins.copyartifact.CopyArtifact.copyOne(CopyArtifact.java:762)
02:10:43  Caused: java.io.IOException: Failed to copy file:/home/jenkins/.jenkins/jobs/build-scripts/jobs/jobs/jobs/jdk17u/jobs/jdk17u-linux-x64-temurin/builds/405/archive/workspace/target/OpenJDK17U-jdk-sources_2023-09-05-23-30.tar.gz to /home/jenkins/.jenkins/workspace/build-scripts/openjdk17-pipeline/target/linux/x64/temurin/OpenJDK17U-jdk-sources_2023-09-05-23-30.tar.gz
02:10:43  	at hudson.plugins.copyartifact.CopyArtifact.copyOne(CopyArtifact.java:768)
02:10:43  	at hudson.plugins.copyartifact.CopyArtifact.copy(CopyArtifact.java:708)
02:10:43  	at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:668)
02:10:43  	at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:552)
02:10:43  	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
02:10:43  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
02:10:43  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
02:10:43  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
02:10:43  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
02:10:43  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02:10:43  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
02:10:43  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
02:10:43  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sophia-guo** [comment]
There are four copy artifact failures due to different reasons. 

This specific **linux-x64** one might be related with reproduce_comparible build, which trigger a new build. If the new build succeeds only its artifacts will be kept all artifacts of the former builds will be deleted in adoptium jenkins. Though have no idea about that message `/home/jenkins/.jenkins/jobs/build-scripts/jobs/jobs/jobs/jdk17u/workspace/jdk17u-linux-x64-temurin@tmp/jfrog/405/.jfrog deleted
`.
If that is the case we can move the job reproduce_comparible after the tests or even after installers to be at the end of all other jobs. @andrew-m-leonard would that be good?

**Comment by sophia-guo** [comment]
The reason the failure is intermittent is if the second build triggered  by reproduce_compare job wait long enough for available agents then it might not happen as the first job has enough time to finish all test jobs and artifacts are available for upstream to copy.
